# Site settings
title: Tableau Web Data Connector
email: jdominguez@tableau.com
description: Connect to your web data to Tableau.
baseurl: "/webdataconnector"
# permalink: pretty
defaults:
  -
    scope:
      path: "" # Apply to all files
    values:
      layout: "default"

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
    toc_levels: 1..3

# Include SEO file for Google rich results
gems:
  - jekyll-seo-tag

# Exclude
exclude: ['node_modules', 'vendor']
